name: build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3.0.2
    -
      name: Setup go
      uses: actions/setup-go@v3
      with:
        stable: true
    -
      name: Download go modules
      run: go mod download
    -
      name: Go build
      run: go build -o /dev/null ./...
